# -*- coding: utf-8 -*-
"""Alpha beta pruning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11CFuqWJ-j_VcLOyN3UyLMofCd8Icofac
"""

def alpha_beta_pruning(node, depth, alpha, beta, maximizing_player, tree):
    if depth == 0 or node not in tree:
        return node  # leaf node value

    if maximizing_player:
        max_eval = float('-inf')
        for child in tree[node]:
            eval = alpha_beta_pruning(child, depth - 1, alpha, beta, False, tree)
            max_eval = max(max_eval, eval)
            alpha = max(alpha, eval)
            if beta <= alpha:
                print(f"Pruned at node {child}")
                break
        return max_eval
    else:
        min_eval = float('inf')
        for child in tree[node]:
            eval = alpha_beta_pruning(child, depth - 1, alpha, beta, True, tree)
            min_eval = min(min_eval, eval)
            beta = min(beta, eval)
            if beta <= alpha:
                print(f"Pruned at node {child}")
                break
        return min_eval

# Example Game Tree (values at leaves)
tree = {
    'A': [3, 5, 6],
}

result = alpha_beta_pruning('A', 1, float('-inf'), float('inf'), True, tree)
print("Optimal Value:", result)