# -*- coding: utf-8 -*-
"""Forward chaining FOL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GIDRw75zrpryLMth-RJem03Der23QH57
"""

from collections import defaultdict, deque

def forward_chaining(KB, query):
    agenda = deque(KB["facts"])
    inferred = defaultdict(bool)
    new_facts = set(KB["facts"])

    while agenda:
        fact = agenda.popleft()
        if fact == query:
            print(f"{query} is TRUE by Forward Chaining.")
            return True

        if not inferred[fact]:
            inferred[fact] = True
            for rule in KB["rules"]:
                # Check if all premises are satisfied
                if all(premise in new_facts for premise in rule["premises"]):
                    conclusion = rule["conclusion"]
                    if conclusion not in new_facts:
                        print(f"Derived: {conclusion}")
                        new_facts.add(conclusion)
                        agenda.append(conclusion)

    print(f"{query} cannot be proven from KB.")
    return False


# --- KNOWLEDGE BASE ---
KB = {
    "facts": [
        "American(Robert)",
        "Missile(T1)",
        "Owns(A, T1)",
        "Enemy(A, America)"
    ],
    "rules": [
        {"premises": ["Missile(T1)"], "conclusion": "Weapon(T1)"},
        {"premises": ["Enemy(A, America)"], "conclusion": "Hostile(A)"},
        {"premises": ["Missile(T1)", "Owns(A, T1)"], "conclusion": "Sells(Robert, T1, A)"},
        {"premises": ["American(Robert)", "Weapon(T1)", "Sells(Robert, T1, A)", "Hostile(A)"], "conclusion": "Criminal(Robert)"}
    ]
}

forward_chaining(KB, "Criminal(Robert)")