# -*- coding: utf-8 -*-
"""Tic tac toe.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-i1lL-gl_a5d-uqNUqFvHgdfvt23qqj3
"""

import random

def print_board(b):
    for r in b: print(" | ".join(r)); print("-"*9)

def win(b,p):
    return any(all(c==p for c in r) for r in b) or \
           any(all(b[i][j]==p for i in range(3)) for j in range(3)) or \
           all(b[i][i]==p for i in range(3)) or \
           all(b[i][2-i]==p for i in range(3))

def full(b): return all(c!=" " for r in b for c in r)

def game():
    b=[[" "]*3 for _ in range(3)]
    print_board(b)
    while 1:
        r,c=map(int,input("Your move (row col 0-2): ").split())
        if 0<=r<3 and 0<=c<3 and b[r][c]==" ":
            b[r][c]="X"; print_board(b)
            if win(b,"X"): print("You win!"); break
            if full(b): print("Draw!"); break
            while 1:
                r,c=random.randint(0,2),random.randint(0,2)
                if b[r][c]==" ": b[r][c]="O"; break
            print("Computer's move:"); print_board(b)
            if win(b,"O"): print("Computer wins!"); break
            if full(b): print("Draw!"); break
        else: print("Invalid")

game()