# -*- coding: utf-8 -*-
"""Unification FOL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dhjfp7k5FqQIueydxDi_fVK4OciELxhr
"""

def is_variable(x):
    return isinstance(x, str) and x[0].islower()

def unify(x, y, substitutions=None):
    if substitutions is None:
        substitutions = {}

    if x == y:
        return substitutions

    if is_variable(x):
        return unify_var(x, y, substitutions)
    elif is_variable(y):
        return unify_var(y, x, substitutions)
    elif isinstance(x, tuple) and isinstance(y, tuple):
        if x[0] != y[0] or len(x[1]) != len(y[1]):
            return None
        for a, b in zip(x[1], y[1]):
            substitutions = unify(a, b, substitutions)
            if substitutions is None:
                return None
        return substitutions
    else:
        return None

def unify_var(var, x, substitutions):
    if var in substitutions:
        return unify(substitutions[var], x, substitutions)
    elif x in substitutions:
        return unify(var, substitutions[x], substitutions)
    elif occurs_check(var, x, substitutions):
        return None
    else:
        substitutions[var] = x
        return substitutions

def occurs_check(var, x, substitutions):
    if var == x:
        return True
    elif isinstance(x, tuple):
        return any(occurs_check(var, arg, substitutions) for arg in x[1])
    elif x in substitutions:
        return occurs_check(var, substitutions[x], substitutions)
    return False

# Example
expr1 = ("Eats", ["x", "Apple"])
expr2 = ("Eats", ["Riya", "y"])
print(unify(expr1, expr2))  # Output: {'x': 'Riya', 'y': 'Apple'}